name: Sync Fork
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: 0 */1 * * *
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
          - uses: tgymnich/fork-sync@v1.2.1
            with:
                owner: scratchaddons-community
                base: main
                head: main
