name: Sync Fork
on:
    workflow_dispatch:
    schedule:
        - cron: 0 */8 * * *

permissions: write-all

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
          - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
            env:
                GITHUB_TOKEN: ${{ github.token }}
                REPOSITORY: ${{ github.repository }}
                BRANCH_NAME: ${{ github.ref_name }}
