name: Sync Fork
on:
    workflow_dispatch:
    schedule:
        - cron: 0 */1 * * *

permissions: write-all

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
          - uses: tgymnich/fork-sync@v1.2.1
            with:
                github_token: ${{ github.token }}
                base: main
                head: main
                owner: scratchaddons-community
